// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-HnceT8Y6dTBg4vGaoSFIcvlsSyfMh3k',
    appId: '1:1034560535939:web:700595df664ca037268ab6',
    messagingSenderId: '1034560535939',
    projectId: 'hellofixer-5d4d6',
    authDomain: 'hellofixer-5d4d6.firebaseapp.com',
    storageBucket: 'hellofixer-5d4d6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOJtqHvmp0IWYuq00furls0QLGSraGSBw',
    appId: '1:1034560535939:android:b3d77cdb11ce203a268ab6',
    messagingSenderId: '1034560535939',
    projectId: 'hellofixer-5d4d6',
    storageBucket: 'hellofixer-5d4d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGpGvam9qG7aBGV3hJwLCymKSKvNIr_yA',
    appId: '1:1034560535939:ios:71bfe6288922a335268ab6',
    messagingSenderId: '1034560535939',
    projectId: 'hellofixer-5d4d6',
    storageBucket: 'hellofixer-5d4d6.firebasestorage.app',
    iosBundleId: 'com.salimrahaman.hellofixer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGpGvam9qG7aBGV3hJwLCymKSKvNIr_yA',
    appId: '1:1034560535939:ios:71bfe6288922a335268ab6',
    messagingSenderId: '1034560535939',
    projectId: 'hellofixer-5d4d6',
    storageBucket: 'hellofixer-5d4d6.firebasestorage.app',
    iosBundleId: 'com.salimrahaman.hellofixer',
  );

}